parameters:
    pusher.options:
        cluster: 'eu'
        useTLS: true
services:
    Pusher\Pusher:
        public: true
        arguments:
            - '%env(PUSHER_KEY)%'
            - '%env(PUSHER_SECRET)%'
            - '%env(PUSHER_APP_ID)%'
            - '%pusher.options%'
