parameters:
    from: '%env(APP_ADMIN)%'
    vat: 14

services:
    _defaults:
        autowire: true
        autoconfigure: true
        ## bind globals arguments
        bind:
            $limitProducts: 20 #always set the limit to 3
            $taxes: '%vat%'
#            $oracleManager: '@doctrine.orm.customer_entity_manager'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\Cart:
#        calls:
#            - method: injectServices
#              arguments:
#                  $logger: '@monolog.logger.event'
        arguments:
            $vat: '%vat%'
            $from: '%from%'

    App\Service\Product:
        lazy: true

    App\Service\Mailer:
        ## factory with a concrete function ##
        factory: 'App\Factory\MailerFactory:createMailer'

        ## factory with  a static function ##
        #factory: ['App\Factory\MailerFactory', 'alertAdmins']

